/*** HELP START ***//*

Macro: SG024
Purpose: Swimmer plot of subject-level treatment duration and events.

*//*** HELP END ***/

%macro SG024;
title "SG024:Swimmer Plot";
%z_dummy_swimmer;
data dummy_swimmer1;
set dummy_swimmer;
select (AVALC);
  when ("CR") CRDY=STDY;
  when ("PR") PRDY=STDY;
  when ("SD") SDDY=STDY;
  when ("PD") PDDY=STDY;
  otherwise;
end;
if PARAMCD="DUR" then do;
  DURSTDY=STDY;
  DURENDY=ENDY;
end;
if PARAMCD="OBS" then do;
  OBSSTDY=STDY;
  OBSENDY=ENDY;
end;
if ONGOING="Y" then highcap ="FilledArrow";
retain yno;
if _N_=1 then yno=0;
L_USUBJID=lag(USUBJID);
if USUBJID ne L_USUBJID then yno +1;

drop L_USUBJID;
run;


ods graphics / 
               noborder
               noscale
               width=980 px
               height=610 px
               attrpriority=none
               imagefmt=png
;
ods proclabel="SG024:Swimmer Plot";
proc sgplot data= dummy_swimmer1 ;
  highlow y=yno low=OBSSTDY high=OBSENDY / highcap=highcap type=bar fill nooutline 
             dataskin=CRISP fillattrs=(color=silver ) lineattrs=(color=black) barwidth=1 ;
  
 highlow y=yno low=DURSTDY high=DURENDY / lineattrs=(thickness=2 color=black ) name='status' legendlabel='Response Duration' ;

  scatter y=yno x=CRDY / markerattrs=(symbol=circlefilled size=8 color=black) name='CR' legendlabel='CR';
  scatter y=yno x=PRDY / markerattrs=(symbol=diamondfilled size=8 color=black) name='PR' legendlabel='PR';
  scatter y=yno x=SDDY / markerattrs=(symbol=squarefilled size=8 color=black) name='SD' legendlabel='SD';
  scatter y=yno x=PDDY / markerattrs=(symbol=X size=8 color=black) name='PD' legendlabel='PD';
  legenditem type=marker name="ongoing" /label="Ongoing" markerattrs=(symbol=trianglerightfilled color=silver size=10 ); 
  yaxistable USUBJID / title=" " label=" " location=inside position=left labelattrs=(size=9) valueattrs=(size=8);
  xaxis label='Day' values=(1 to 365 by 14 )  offsetmax=0.05;
  yaxis reverse display=(noticks novalues noline) label='Participants' min=1 max=20 offsetmin=0 ;
  keylegend 'ongoing' 'CR' 'PR' 'SD'  'PD'  'status'/  location=inside position=topright across=1;
  run;

ods proclabel="SG024:Swimmer Plot";
proc odstext;
p'data(*ESC*){unicode "00A0"x}dummy_swimmer;';
p'  length USUBJID $8 PARAMCD $12 PARAM $40 AVALC ONGOING $2;';
p'  USUBJID="SUBJ001"; PARAMCD="OBS";  PARAM="Observation period"; STDY=1;   ENDY=210; AVALC="";   ONGOING="Y"; output;';
p'  USUBJID="SUBJ001"; PARAMCD="RESP"; PARAM="Overall response";   STDY=28;  ENDY=.;   AVALC="SD"; ONGOING="";  output;';
p'  USUBJID="SUBJ001"; PARAMCD="RESP"; PARAM="Overall response";   STDY=56;  ENDY=.;   AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ001"; PARAMCD="RESP"; PARAM="Overall response";   STDY=84;  ENDY=.;   AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ001"; PARAMCD="RESP"; PARAM="Overall response";   STDY=140; ENDY=.;   AVALC="CR"; ONGOING="";  output;';
p'  USUBJID="SUBJ001"; PARAMCD="RESP"; PARAM="Overall response";   STDY=196; ENDY=.;   AVALC="CR"; ONGOING="";  output;';
p'  USUBJID="SUBJ001"; PARAMCD="DUR";  PARAM="Response duration";  STDY=56;  ENDY=196; AVALC="CR"; ONGOING="";  output;';
p'  USUBJID="SUBJ002"; PARAMCD="OBS";  PARAM="Observation period"; STDY=1;   ENDY=168; AVALC="";   ONGOING="N"; output;';
p'  USUBJID="SUBJ002"; PARAMCD="RESP"; PARAM="Overall response";   STDY=21;  ENDY=.;   AVALC="SD"; ONGOING="";  output;';
p'  USUBJID="SUBJ002"; PARAMCD="RESP"; PARAM="Overall response";   STDY=42;  ENDY=.;   AVALC="SD"; ONGOING="";  output;';
p'  USUBJID="SUBJ002"; PARAMCD="RESP"; PARAM="Overall response";   STDY=63;  ENDY=.;   AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ002"; PARAMCD="RESP"; PARAM="Overall response";   STDY=105; ENDY=.;   AVALC="PD"; ONGOING="";  output;';
p'  USUBJID="SUBJ002"; PARAMCD="DUR";  PARAM="Response duration";  STDY=63;  ENDY=105; AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ003"; PARAMCD="OBS";  PARAM="Observation period"; STDY=1;   ENDY=252; AVALC="";   ONGOING="N"; output;';
p'  USUBJID="SUBJ003"; PARAMCD="RESP"; PARAM="Overall response";   STDY=28;  ENDY=.;   AVALC="SD"; ONGOING="";  output;';
p'  USUBJID="SUBJ003"; PARAMCD="RESP"; PARAM="Overall response";   STDY=56;  ENDY=.;   AVALC="SD"; ONGOING="";  output;';
p'  USUBJID="SUBJ003"; PARAMCD="RESP"; PARAM="Overall response";   STDY=84;  ENDY=.;   AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ003"; PARAMCD="RESP"; PARAM="Overall response";   STDY=112; ENDY=.;   AVALC="CR"; ONGOING="";  output;';
p'  USUBJID="SUBJ003"; PARAMCD="RESP"; PARAM="Overall response";   STDY=168; ENDY=.;   AVALC="CR"; ONGOING="";  output;';
p'  USUBJID="SUBJ003"; PARAMCD="RESP"; PARAM="Overall response";   STDY=224; ENDY=.;   AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ003"; PARAMCD="DUR";  PARAM="Response duration";  STDY=84;  ENDY=224; AVALC="CR"; ONGOING="";  output;';
p'  USUBJID="SUBJ004"; PARAMCD="OBS";  PARAM="Observation period"; STDY=1;   ENDY=98;  AVALC="";   ONGOING="Y"; output;';
p'  USUBJID="SUBJ004"; PARAMCD="RESP"; PARAM="Overall response";   STDY=14;  ENDY=.;   AVALC="SD"; ONGOING="";  output;';
p'  USUBJID="SUBJ004"; PARAMCD="RESP"; PARAM="Overall response";   STDY=28;  ENDY=.;   AVALC="SD"; ONGOING="";  output;';
p'  USUBJID="SUBJ004"; PARAMCD="RESP"; PARAM="Overall response";   STDY=56;  ENDY=.;   AVALC="PD"; ONGOING="";  output;';
p'  USUBJID="SUBJ005"; PARAMCD="OBS";  PARAM="Observation period"; STDY=1;   ENDY=301; AVALC="";   ONGOING="Y"; output;';
p'  USUBJID="SUBJ005"; PARAMCD="RESP"; PARAM="Overall response";   STDY=30;  ENDY=.;   AVALC="SD"; ONGOING="";  output;';
p'  USUBJID="SUBJ005"; PARAMCD="RESP"; PARAM="Overall response";   STDY=60;  ENDY=.;   AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ005"; PARAMCD="RESP"; PARAM="Overall response";   STDY=90;  ENDY=.;   AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ005"; PARAMCD="RESP"; PARAM="Overall response";   STDY=150; ENDY=.;   AVALC="CR"; ONGOING="";  output;';
p'  USUBJID="SUBJ005"; PARAMCD="RESP"; PARAM="Overall response";   STDY=210; ENDY=.;   AVALC="CR"; ONGOING="";  output;';
p'  USUBJID="SUBJ005"; PARAMCD="RESP"; PARAM="Overall response";   STDY=270; ENDY=.;   AVALC="CR"; ONGOING="";  output;';
p'  USUBJID="SUBJ005"; PARAMCD="DUR";  PARAM="Response duration";  STDY=60;  ENDY=270; AVALC="CR"; ONGOING="";  output;';
p'  USUBJID="SUBJ006"; PARAMCD="OBS";  PARAM="Observation period"; STDY=1;   ENDY=126; AVALC="";   ONGOING="N"; output;';
p'  USUBJID="SUBJ006"; PARAMCD="RESP"; PARAM="Overall response";   STDY=21;  ENDY=.;   AVALC="SD"; ONGOING="";  output;';
p'  USUBJID="SUBJ006"; PARAMCD="RESP"; PARAM="Overall response";   STDY=42;  ENDY=.;   AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ006"; PARAMCD="RESP"; PARAM="Overall response";   STDY=63;  ENDY=.;   AVALC="SD"; ONGOING="";  output;';
p'  USUBJID="SUBJ006"; PARAMCD="RESP"; PARAM="Overall response";   STDY=84;  ENDY=.;   AVALC="PD"; ONGOING="";  output;';
p'  USUBJID="SUBJ006"; PARAMCD="DUR";  PARAM="Response duration";  STDY=42;  ENDY=63;  AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ007"; PARAMCD="OBS";  PARAM="Observation period"; STDY=1;   ENDY=224; AVALC="";   ONGOING="N"; output;';
p'  USUBJID="SUBJ007"; PARAMCD="RESP"; PARAM="Overall response";   STDY=28;  ENDY=.;   AVALC="SD"; ONGOING="";  output;';
p'  USUBJID="SUBJ007"; PARAMCD="RESP"; PARAM="Overall response";   STDY=56;  ENDY=.;   AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ007"; PARAMCD="RESP"; PARAM="Overall response";   STDY=112; ENDY=.;   AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ007"; PARAMCD="RESP"; PARAM="Overall response";   STDY=168; ENDY=.;   AVALC="SD"; ONGOING="";  output;';
p'  USUBJID="SUBJ007"; PARAMCD="RESP"; PARAM="Overall response";   STDY=210; ENDY=.;   AVALC="PD"; ONGOING="";  output;';
p'  USUBJID="SUBJ007"; PARAMCD="DUR";  PARAM="Response duration";  STDY=56;  ENDY=112; AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ008"; PARAMCD="OBS";  PARAM="Observation period"; STDY=1;   ENDY=182; AVALC="";   ONGOING="Y"; output;';
p'  USUBJID="SUBJ008"; PARAMCD="RESP"; PARAM="Overall response";   STDY=26;  ENDY=.;   AVALC="SD"; ONGOING="";  output;';
p'  USUBJID="SUBJ008"; PARAMCD="RESP"; PARAM="Overall response";   STDY=52;  ENDY=.;   AVALC="SD"; ONGOING="";  output;';
p'  USUBJID="SUBJ008"; PARAMCD="RESP"; PARAM="Overall response";   STDY=78;  ENDY=.;   AVALC="SD"; ONGOING="";  output;';
p'  USUBJID="SUBJ008"; PARAMCD="RESP"; PARAM="Overall response";   STDY=130; ENDY=.;   AVALC="PD"; ONGOING="";  output;';
p'  USUBJID="SUBJ009"; PARAMCD="OBS";  PARAM="Observation period"; STDY=1;   ENDY=336; AVALC="";   ONGOING="N"; output;';
p'  USUBJID="SUBJ009"; PARAMCD="RESP"; PARAM="Overall response";   STDY=28;  ENDY=.;   AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ009"; PARAMCD="RESP"; PARAM="Overall response";   STDY=56;  ENDY=.;   AVALC="CR"; ONGOING="";  output;';
p'  USUBJID="SUBJ009"; PARAMCD="RESP"; PARAM="Overall response";   STDY=84;  ENDY=.;   AVALC="CR"; ONGOING="";  output;';
p'  USUBJID="SUBJ009"; PARAMCD="RESP"; PARAM="Overall response";   STDY=140; ENDY=.;   AVALC="CR"; ONGOING="";  output;';
p'  USUBJID="SUBJ009"; PARAMCD="RESP"; PARAM="Overall response";   STDY=196; ENDY=.;   AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ009"; PARAMCD="RESP"; PARAM="Overall response";   STDY=280; ENDY=.;   AVALC="SD"; ONGOING="";  output;';
p'  USUBJID="SUBJ009"; PARAMCD="DUR";  PARAM="Response duration";  STDY=28;  ENDY=196; AVALC="CR"; ONGOING="";  output;';
p'  USUBJID="SUBJ010"; PARAMCD="OBS";  PARAM="Observation period"; STDY=1;   ENDY=154; AVALC="";   ONGOING="Y"; output;';
p'  USUBJID="SUBJ010"; PARAMCD="RESP"; PARAM="Overall response";   STDY=22;  ENDY=.;   AVALC="SD"; ONGOING="";  output;';
p'  USUBJID="SUBJ010"; PARAMCD="RESP"; PARAM="Overall response";   STDY=44;  ENDY=.;   AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ010"; PARAMCD="RESP"; PARAM="Overall response";   STDY=88;  ENDY=.;   AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ010"; PARAMCD="RESP"; PARAM="Overall response";   STDY=132; ENDY=.;   AVALC="PD"; ONGOING="";  output;';
p'  USUBJID="SUBJ010"; PARAMCD="DUR";  PARAM="Response duration";  STDY=44;  ENDY=88;  AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ011"; PARAMCD="OBS";  PARAM="Observation period"; STDY=1;   ENDY=275; AVALC="";   ONGOING="N"; output;';
p'  USUBJID="SUBJ011"; PARAMCD="RESP"; PARAM="Overall response";   STDY=25;  ENDY=.;   AVALC="SD"; ONGOING="";  output;';
p'  USUBJID="SUBJ011"; PARAMCD="RESP"; PARAM="Overall response";   STDY=50;  ENDY=.;   AVALC="SD"; ONGOING="";  output;';
p'  USUBJID="SUBJ011"; PARAMCD="RESP"; PARAM="Overall response";   STDY=75;  ENDY=.;   AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ011"; PARAMCD="RESP"; PARAM="Overall response";   STDY=125; ENDY=.;   AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ011"; PARAMCD="RESP"; PARAM="Overall response";   STDY=175; ENDY=.;   AVALC="CR"; ONGOING="";  output;';
p'  USUBJID="SUBJ011"; PARAMCD="RESP"; PARAM="Overall response";   STDY=225; ENDY=.;   AVALC="CR"; ONGOING="";  output;';
p'  USUBJID="SUBJ011"; PARAMCD="DUR";  PARAM="Response duration";  STDY=75;  ENDY=225; AVALC="CR"; ONGOING="";  output;';
p'  USUBJID="SUBJ012"; PARAMCD="OBS";  PARAM="Observation period"; STDY=1;   ENDY=119; AVALC="";   ONGOING="N"; output;';
p'  USUBJID="SUBJ012"; PARAMCD="RESP"; PARAM="Overall response";   STDY=17;  ENDY=.;   AVALC="SD"; ONGOING="";  output;';
p'  USUBJID="SUBJ012"; PARAMCD="RESP"; PARAM="Overall response";   STDY=34;  ENDY=.;   AVALC="SD"; ONGOING="";  output;';
p'  USUBJID="SUBJ012"; PARAMCD="RESP"; PARAM="Overall response";   STDY=68;  ENDY=.;   AVALC="PD"; ONGOING="";  output;';
p'  USUBJID="SUBJ013"; PARAMCD="OBS";  PARAM="Observation period"; STDY=1;   ENDY=245; AVALC="";   ONGOING="N"; output;';
p'  USUBJID="SUBJ013"; PARAMCD="RESP"; PARAM="Overall response";   STDY=35;  ENDY=.;   AVALC="SD"; ONGOING="";  output;';
p'  USUBJID="SUBJ013"; PARAMCD="RESP"; PARAM="Overall response";   STDY=70;  ENDY=.;   AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ013"; PARAMCD="RESP"; PARAM="Overall response";   STDY=105; ENDY=.;   AVALC="SD"; ONGOING="";  output;';
p'  USUBJID="SUBJ013"; PARAMCD="RESP"; PARAM="Overall response";   STDY=140; ENDY=.;   AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ013"; PARAMCD="RESP"; PARAM="Overall response";   STDY=210; ENDY=.;   AVALC="PD"; ONGOING="";  output;';
p'  USUBJID="SUBJ013"; PARAMCD="DUR";  PARAM="Response duration";  STDY=70;  ENDY=70;  AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ013"; PARAMCD="DUR";  PARAM="Response duration";  STDY=140; ENDY=140; AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ014"; PARAMCD="OBS";  PARAM="Observation period"; STDY=1;   ENDY=196; AVALC="";   ONGOING="Y"; output;';
p'  USUBJID="SUBJ014"; PARAMCD="RESP"; PARAM="Overall response";   STDY=28;  ENDY=.;   AVALC="SD"; ONGOING="";  output;';
p'  USUBJID="SUBJ014"; PARAMCD="RESP"; PARAM="Overall response";   STDY=56;  ENDY=.;   AVALC="SD"; ONGOING="";  output;';
p'  USUBJID="SUBJ014"; PARAMCD="RESP"; PARAM="Overall response";   STDY=84;  ENDY=.;   AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ014"; PARAMCD="RESP"; PARAM="Overall response";   STDY=112; ENDY=.;   AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ014"; PARAMCD="RESP"; PARAM="Overall response";   STDY=168; ENDY=.;   AVALC="SD"; ONGOING="";  output;';
p'  USUBJID="SUBJ014"; PARAMCD="DUR";  PARAM="Response duration";  STDY=84;  ENDY=112; AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ015"; PARAMCD="OBS";  PARAM="Observation period"; STDY=1;   ENDY=322; AVALC="";   ONGOING="N"; output;';
p'  USUBJID="SUBJ015"; PARAMCD="RESP"; PARAM="Overall response";   STDY=46;  ENDY=.;   AVALC="SD"; ONGOING="";  output;';
p'  USUBJID="SUBJ015"; PARAMCD="RESP"; PARAM="Overall response";   STDY=92;  ENDY=.;   AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ015"; PARAMCD="RESP"; PARAM="Overall response";   STDY=138; ENDY=.;   AVALC="CR"; ONGOING="";  output;';
p'  USUBJID="SUBJ015"; PARAMCD="RESP"; PARAM="Overall response";   STDY=184; ENDY=.;   AVALC="CR"; ONGOING="";  output;';
p'  USUBJID="SUBJ015"; PARAMCD="RESP"; PARAM="Overall response";   STDY=230; ENDY=.;   AVALC="CR"; ONGOING="";  output;';
p'  USUBJID="SUBJ015"; PARAMCD="RESP"; PARAM="Overall response";   STDY=276; ENDY=.;   AVALC="CR"; ONGOING="";  output;';
p'  USUBJID="SUBJ015"; PARAMCD="DUR";  PARAM="Response duration";  STDY=92;  ENDY=276; AVALC="CR"; ONGOING="";  output;';
p'  USUBJID="SUBJ016"; PARAMCD="OBS";  PARAM="Observation period"; STDY=1;   ENDY=147; AVALC="";   ONGOING="N"; output;';
p'  USUBJID="SUBJ016"; PARAMCD="RESP"; PARAM="Overall response";   STDY=21;  ENDY=.;   AVALC="SD"; ONGOING="";  output;';
p'  USUBJID="SUBJ016"; PARAMCD="RESP"; PARAM="Overall response";   STDY=42;  ENDY=.;   AVALC="SD"; ONGOING="";  output;';
p'  USUBJID="SUBJ016"; PARAMCD="RESP"; PARAM="Overall response";   STDY=63;  ENDY=.;   AVALC="SD"; ONGOING="";  output;';
p'  USUBJID="SUBJ016"; PARAMCD="RESP"; PARAM="Overall response";   STDY=105; ENDY=.;   AVALC="PD"; ONGOING="";  output;';
p'  USUBJID="SUBJ017"; PARAMCD="OBS";  PARAM="Observation period"; STDY=1;   ENDY=287; AVALC="";   ONGOING="N"; output;';
p'  USUBJID="SUBJ017"; PARAMCD="RESP"; PARAM="Overall response";   STDY=41;  ENDY=.;   AVALC="SD"; ONGOING="";  output;';
p'  USUBJID="SUBJ017"; PARAMCD="RESP"; PARAM="Overall response";   STDY=82;  ENDY=.;   AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ017"; PARAMCD="RESP"; PARAM="Overall response";   STDY=123; ENDY=.;   AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ017"; PARAMCD="RESP"; PARAM="Overall response";   STDY=164; ENDY=.;   AVALC="CR"; ONGOING="";  output;';
p'  USUBJID="SUBJ017"; PARAMCD="RESP"; PARAM="Overall response";   STDY=205; ENDY=.;   AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ017"; PARAMCD="RESP"; PARAM="Overall response";   STDY=246; ENDY=.;   AVALC="PD"; ONGOING="";  output;';
p'  USUBJID="SUBJ017"; PARAMCD="DUR";  PARAM="Response duration";  STDY=82;  ENDY=205; AVALC="CR"; ONGOING="";  output;';
p'  USUBJID="SUBJ018"; PARAMCD="OBS";  PARAM="Observation period"; STDY=1;   ENDY=203; AVALC="";   ONGOING="N"; output;';
p'  USUBJID="SUBJ018"; PARAMCD="RESP"; PARAM="Overall response";   STDY=29;  ENDY=.;   AVALC="SD"; ONGOING="";  output;';
p'  USUBJID="SUBJ018"; PARAMCD="RESP"; PARAM="Overall response";   STDY=58;  ENDY=.;   AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ018"; PARAMCD="RESP"; PARAM="Overall response";   STDY=87;  ENDY=.;   AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ018"; PARAMCD="RESP"; PARAM="Overall response";   STDY=145; ENDY=.;   AVALC="PD"; ONGOING="";  output;';
p'  USUBJID="SUBJ018"; PARAMCD="DUR";  PARAM="Response duration";  STDY=58;  ENDY=87;  AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ019"; PARAMCD="OBS";  PARAM="Observation period"; STDY=1;   ENDY=364; AVALC="";   ONGOING="Y"; output;';
p'  USUBJID="SUBJ019"; PARAMCD="RESP"; PARAM="Overall response";   STDY=28;  ENDY=.;   AVALC="SD"; ONGOING="";  output;';
p'  USUBJID="SUBJ019"; PARAMCD="RESP"; PARAM="Overall response";   STDY=56;  ENDY=.;   AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ019"; PARAMCD="RESP"; PARAM="Overall response";   STDY=84;  ENDY=.;   AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ019"; PARAMCD="RESP"; PARAM="Overall response";   STDY=112; ENDY=.;   AVALC="CR"; ONGOING="";  output;';
p'  USUBJID="SUBJ019"; PARAMCD="RESP"; PARAM="Overall response";   STDY=168; ENDY=.;   AVALC="CR"; ONGOING="";  output;';
p'  USUBJID="SUBJ019"; PARAMCD="RESP"; PARAM="Overall response";   STDY=224; ENDY=.;   AVALC="CR"; ONGOING="";  output;';
p'  USUBJID="SUBJ019"; PARAMCD="RESP"; PARAM="Overall response";   STDY=280; ENDY=.;   AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ019"; PARAMCD="RESP"; PARAM="Overall response";   STDY=336; ENDY=.;   AVALC="SD"; ONGOING="";  output;';
p'  USUBJID="SUBJ019"; PARAMCD="DUR";  PARAM="Response duration";  STDY=56;  ENDY=280; AVALC="CR"; ONGOING="";  output;';
p'  USUBJID="SUBJ020"; PARAMCD="OBS";  PARAM="Observation period"; STDY=1;   ENDY=175; AVALC="";   ONGOING="Y"; output;';
p'  USUBJID="SUBJ020"; PARAMCD="RESP"; PARAM="Overall response";   STDY=25;  ENDY=.;   AVALC="SD"; ONGOING="";  output;';
p'  USUBJID="SUBJ020"; PARAMCD="RESP"; PARAM="Overall response";   STDY=50;  ENDY=.;   AVALC="SD"; ONGOING="";  output;';
p'  USUBJID="SUBJ020"; PARAMCD="RESP"; PARAM="Overall response";   STDY=75;  ENDY=.;   AVALC="PR"; ONGOING="";  output;';
p'  USUBJID="SUBJ020"; PARAMCD="RESP"; PARAM="Overall response";   STDY=100; ENDY=.;   AVALC="PD"; ONGOING="";  output;';
p'  USUBJID="SUBJ020"; PARAMCD="DUR";  PARAM="Response duration";  STDY=75;  ENDY=75;  AVALC="PR"; ONGOING="";  output;';
p'run;';
p'';
p'data(*ESC*){unicode "00A0"x}dummy_swimmer1;';
p'set(*ESC*){unicode "00A0"x}dummy_swimmer;';
p'select(*ESC*){unicode "00A0"x}(AVALC);';
p'(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}when(*ESC*){unicode "00A0"x}("CR")(*ESC*){unicode "00A0"x}CRDY=STDY;';
p'(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}when(*ESC*){unicode "00A0"x}("PR")(*ESC*){unicode "00A0"x}PRDY=STDY;';
p'(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}when(*ESC*){unicode "00A0"x}("SD")(*ESC*){unicode "00A0"x}SDDY=STDY;';
p'(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}when(*ESC*){unicode "00A0"x}("PD")(*ESC*){unicode "00A0"x}PDDY=STDY;';
p'(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}otherwise;';
p'end;';
p'if(*ESC*){unicode "00A0"x}PARAMCD="DUR"(*ESC*){unicode "00A0"x}then(*ESC*){unicode "00A0"x}do;';
p'(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}DURSTDY=STDY;';
p'(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}DURENDY=ENDY;';
p'end;';
p'if(*ESC*){unicode "00A0"x}PARAMCD="OBS"(*ESC*){unicode "00A0"x}then(*ESC*){unicode "00A0"x}do;';
p'(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}OBSSTDY=STDY;';
p'(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}OBSENDY=ENDY;';
p'end;';
p'if(*ESC*){unicode "00A0"x}ONGOING="Y"(*ESC*){unicode "00A0"x}then(*ESC*){unicode "00A0"x}highcap(*ESC*){unicode "00A0"x}="FilledArrow";';
p'retain(*ESC*){unicode "00A0"x}yno;';
p'if(*ESC*){unicode "00A0"x}_N_=1(*ESC*){unicode "00A0"x}then(*ESC*){unicode "00A0"x}yno=0;';
p'L_USUBJID=lag(USUBJID);';
p'if(*ESC*){unicode "00A0"x}USUBJID(*ESC*){unicode "00A0"x}ne(*ESC*){unicode "00A0"x}L_USUBJID(*ESC*){unicode "00A0"x}then(*ESC*){unicode "00A0"x}yno(*ESC*){unicode "00A0"x}+1;';
p'';
p'drop(*ESC*){unicode "00A0"x}L_USUBJID;';
p'run;';
p'';
p'ods(*ESC*){unicode "00A0"x}graphics(*ESC*){unicode "00A0"x}/(*ESC*){unicode "00A0"x}reset';
p'(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}noborder';
p'(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}noscale';
p'(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}width=980(*ESC*){unicode "00A0"x}px';
p'(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}height=610(*ESC*){unicode "00A0"x}px';
p'(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}attrpriority=none';
p'(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}imagefmt=png';
p'proc(*ESC*){unicode "00A0"x}sgplot(*ESC*){unicode "00A0"x}data=(*ESC*){unicode "00A0"x}dummy_swimmer1(*ESC*){unicode "00A0"x};';
p'(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}highlow(*ESC*){unicode "00A0"x}y=yno(*ESC*){unicode "00A0"x}low=OBSSTDY(*ESC*){unicode "00A0"x}high=OBSENDY(*ESC*){unicode "00A0"x}/(*ESC*){unicode "00A0"x}highcap=highcap(*ESC*){unicode "00A0"x}type=bar(*ESC*){unicode "00A0"x}fill(*ESC*){unicode "00A0"x}nooutline(*ESC*){unicode "00A0"x}';
p'(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}dataskin=CRISP(*ESC*){unicode "00A0"x}fillattrs=(color=silver(*ESC*){unicode "00A0"x})(*ESC*){unicode "00A0"x}lineattrs=(color=black)(*ESC*){unicode "00A0"x}barwidth=1(*ESC*){unicode "00A0"x};';
p'(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}';
p'(*ESC*){unicode "00A0"x}highlow(*ESC*){unicode "00A0"x}y=yno(*ESC*){unicode "00A0"x}low=DURSTDY(*ESC*){unicode "00A0"x}high=DURENDY(*ESC*){unicode "00A0"x}/(*ESC*){unicode "00A0"x}lineattrs=(thickness=2(*ESC*){unicode "00A0"x}color=black)(*ESC*){unicode "00A0"x}name="status"(*ESC*){unicode "00A0"x}legendlabel="Response(*ESC*){unicode "00A0"x}Duration"(*ESC*){unicode "00A0"x};';
p'(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}scatter(*ESC*){unicode "00A0"x}y=yno(*ESC*){unicode "00A0"x}x=CRDY(*ESC*){unicode "00A0"x}/(*ESC*){unicode "00A0"x}markerattrs=(symbol=circlefilled(*ESC*){unicode "00A0"x}size=8(*ESC*){unicode "00A0"x}color=black)(*ESC*){unicode "00A0"x}name="CR"(*ESC*){unicode "00A0"x}legendlabel="CR";';
p'(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}scatter(*ESC*){unicode "00A0"x}y=yno(*ESC*){unicode "00A0"x}x=PRDY(*ESC*){unicode "00A0"x}/(*ESC*){unicode "00A0"x}markerattrs=(symbol=diamondfilled(*ESC*){unicode "00A0"x}size=8(*ESC*){unicode "00A0"x}color=black)(*ESC*){unicode "00A0"x}name="PR"(*ESC*){unicode "00A0"x}legendlabel="PR";';
p'(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}scatter(*ESC*){unicode "00A0"x}y=yno(*ESC*){unicode "00A0"x}x=SDDY(*ESC*){unicode "00A0"x}/(*ESC*){unicode "00A0"x}markerattrs=(symbol=squarefilled(*ESC*){unicode "00A0"x}size=8(*ESC*){unicode "00A0"x}color=black)(*ESC*){unicode "00A0"x}name="SD"(*ESC*){unicode "00A0"x}legendlabel="SD";';
p'(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}scatter(*ESC*){unicode "00A0"x}y=yno(*ESC*){unicode "00A0"x}x=PDDY(*ESC*){unicode "00A0"x}/(*ESC*){unicode "00A0"x}markerattrs=(symbol=X(*ESC*){unicode "00A0"x}size=8(*ESC*){unicode "00A0"x}color=black)(*ESC*){unicode "00A0"x}name="PD"(*ESC*){unicode "00A0"x}legendlabel="PD";';
p'(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}legenditem(*ESC*){unicode "00A0"x}type=marker(*ESC*){unicode "00A0"x}name="ongoing"(*ESC*){unicode "00A0"x}/label="Ongoing"(*ESC*){unicode "00A0"x}markerattrs=(symbol=trianglerightfilled(*ESC*){unicode "00A0"x}color=silver(*ESC*){unicode "00A0"x}size=10(*ESC*){unicode "00A0"x});(*ESC*){unicode "00A0"x}';
p'(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}yaxistable(*ESC*){unicode "00A0"x}USUBJID(*ESC*){unicode "00A0"x}/(*ESC*){unicode "00A0"x}title="(*ESC*){unicode "00A0"x}"(*ESC*){unicode "00A0"x}label="(*ESC*){unicode "00A0"x}"(*ESC*){unicode "00A0"x}location=inside(*ESC*){unicode "00A0"x}position=left(*ESC*){unicode "00A0"x}labelattrs=(size=9)(*ESC*){unicode "00A0"x}valueattrs=(size=8);';
p'(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}xaxis(*ESC*){unicode "00A0"x}label="Day"(*ESC*){unicode "00A0"x}values=(1(*ESC*){unicode "00A0"x}to(*ESC*){unicode "00A0"x}365(*ESC*){unicode "00A0"x}by(*ESC*){unicode "00A0"x}14(*ESC*){unicode "00A0"x})(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}offsetmax=0.05;';
p'(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}yaxis(*ESC*){unicode "00A0"x}reverse(*ESC*){unicode "00A0"x}display=(noticks(*ESC*){unicode "00A0"x}novalues(*ESC*){unicode "00A0"x}noline)(*ESC*){unicode "00A0"x}label="Participants"(*ESC*){unicode "00A0"x}min=1(*ESC*){unicode "00A0"x}max=20(*ESC*){unicode "00A0"x}offsetmin=0(*ESC*){unicode "00A0"x};';
p'(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}keylegend(*ESC*){unicode "00A0"x}"ongoing"(*ESC*){unicode "00A0"x}"CR"(*ESC*){unicode "00A0"x}"PR"(*ESC*){unicode "00A0"x}"SD"(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}"PD"(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}"status"/(*ESC*){unicode "00A0"x}(*ESC*){unicode "00A0"x}location=inside(*ESC*){unicode "00A0"x}position=topright(*ESC*){unicode "00A0"x}across=1;';
p'run;';
run;
title ;
%mend;
